# Dependencies
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Permalinks
permalink:        pretty

plugins: [jekyll-paginate]

avatar: http://www.gravatar.com/avatar/56638a47c37d0aa95b2034fda473e119?s=256
baseurl: "/blog"

# Setup
title:            Ryan Stringham
tagline:          Software Engineer
description:      'A blog by Ryan Stringham'
url:              stringham.me/blog

author:
  name:           'Ryan Stringham'
  url:            https://stringham.me

paginate:         5

# Custom vars
